PackageIdentifier: NAV.naisdevice
PackageVersion: 2021-05-28-085435
PackageName: naisdevice
Publisher: NAV
License: MIT
LicenseUrl: https://github.com/nais/device/blob/master/LICENSE
Tags:
- vpn
- security
- nais
- nav
PackageUrl: https://github.com/nais/device
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nais/device/releases/download/2021-05-28-085435/naisdevice.msi
  InstallerSha256: 8a3ecc35d731710cfdeb5d810238ed5000e8357b73b4cef842f6c9376c524e65
  InstallerType: msi
ShortDescription: A mechanism enabling NAVs developers to connect to internal resources in a secure and friendly manner.
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
